Zy/18 app version
anusii/solid pull request #28
Opened 2024-01-04 03:51 UTC by zheyxu

For issue #18

2024-01-04 07:56 UTC, gjwgit requested changes

2024-01-04 07:56 UTC, gjwgit commented on lib/src/solid_login.dart
No. I was hoping we can extract the version information inside SolidLogin, not from the app. This way, we encapsulate the code in the solid package and make it easier for the app developer not to have to work out how to do that.

2024-01-04 23:48 UTC, zheyxu commented on lib/src/solid_login.dart
Run the keypod app, the version information can only be retrieved from pubspec.yaml in keypod app. Modify version information in pubsepc.yaml in solid project does not work.

2024-01-04 23:51 UTC, zheyxu commented on lib/src/solid_login.dart
There's a limitation package_info_plus can only access predefined fields such as version, buildNumber, etc. It doesn't provide direct access to custom fields like app_version defined in pubspec.yaml.

2024-01-05 00:35 UTC, gjwgit commented on lib/src/solid_login.dart
Yes, I want the version from the keypod app to be displayed. The version of solid is not relevant to the app developer. If you have PackageInfo in solid, it gets the information from the current app, not solid. So that is what is required.

2024-01-05 07:44 UTC, gjwgit approved these changes

2024-01-05 09:00 UTC, merged